### ISSUE TITLE
Add Event to google calendar shows "Invalid Request"

### ISSUE THREAD

**Issue by erither** [Rycochet/Chrome#7]
First, I wanted to thank you for writing this extension. It is amazing and makes the fetlife experience much better.

The issue is that when you go to an event and click on the google calendar icon to add the event to your google calendar, it redirects to a page that shows "Invalid Request"

Google may have updated something that broke the extension....

![untitled](https://cloud.githubusercontent.com/assets/20946299/17549807/ea7a1c0a-5ea6-11e6-9979-4ec00b58e789.jpg)
![untitled 1](https://cloud.githubusercontent.com/assets/20946299/17549813/ee77d6ee-5ea6-11e6-9a98-efad05bd8e5f.jpg)

**Comment by Rycochet** [comment]
Ok, was using it yesterday and it worked ok, and literally just tried now and it worked ok - so possibly something to do with setup etc...

Can you confirm that going to [Google Calendar](https://calendar.google.com/calendar/render) actually shows you a calendar? I'm assuming that'll work, but want to  check the obvious .com / tld first ;-)

My second (and more likely) guess is that something is wrong with the url - can you link me to the event you're trying to add - I've got a feeling that it might have too much text in it, so we simply need to reduce the length of the text...

**Comment by Rycochet** [comment]
Just found an event that makes the request too long, will start looking into this tonight :-)

**Comment by erither** [comment]
Thanks. Actually for some reason it's working today. I'm not sure what is different but I was able to add the event I was looking at. I had just installed the extension recently though.

Here is the event:

https://fetlife.com/events/371793

Thanks for looking into it.

On Thu, Aug 11, 2016 at 4:51 AM, Rycochet <notifications@github.com<mailto:notifications@github.com>> wrote:

Just found an event that makes the request too long, will start looking into this tonight :-)

**Comment by Rycochet** [comment]
I've shortened the events, not sure if that'll fix the "Invalid request" error, but I saw that when they were slightly above the limit I decided on - could do with better limiting it (something to take into account the entire length of the string etc), but should reduce the occurrence somewhat :-)
